language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync
 
script:
  - xbuild ./src/Skahal.Infrastructure.Framework.sln /property:"Configuration=OSX;Platform=Any CPU" /p:"DefineConstants=TRAVIS_CI"
  - nunit-console ./src/Skahal.Infrastructure.Framework.UnitTests/bin/OSX/Skahal.Infrastructure.Framework.UnitTests.dll
